# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eigen_Xt_times_diag_w_times_X_cpp <- function(X, w, n_cores) {
    .Call(`_fastLogisticRegressionWrap_eigen_Xt_times_diag_w_times_X_cpp`, X, w, n_cores)
}

eigen_inv_cpp <- function(X, n_cores) {
    .Call(`_fastLogisticRegressionWrap_eigen_inv_cpp`, X, n_cores)
}

eigen_det_cpp <- function(X, n_cores) {
    .Call(`_fastLogisticRegressionWrap_eigen_det_cpp`, X, n_cores)
}

eigen_compute_single_entry_of_diagonal_matrix_cpp <- function(M, j, n_cores) {
    .Call(`_fastLogisticRegressionWrap_eigen_compute_single_entry_of_diagonal_matrix_cpp`, M, j, n_cores)
}

fast_two_by_two_binary_table_cpp <- function(ybin, yhat) {
    .Call(`_fastLogisticRegressionWrap_fast_two_by_two_binary_table_cpp`, ybin, yhat)
}

